POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Classroom Mamation Fest",
  "details": null,
  "maximumAttendees": 2
}

###

POST http://localhost:3333/events/1d08d08f-e871-43c2-b19c-0f7d2d8f31cd/attendees
Content-Type: application/json

{
  "name": "Vitor Alexandre",
  "email": "moto@gmail.com"
}

###

GET http://localhost:3333/events/1d08d08f-e871-43c2-b19c-0f7d2d8f31cd

###

GET http://localhost:3333/attendees/4/badge